# Generated by Django 5.2.13 on 2026-04-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0244_recipeuserweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recommendation_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
