# Generated by Django 5.2.13 on 2026-06-17 20:04

from django.db import migrations, models
from django.db.models import F


def backfill_last_verified(apps, schema_editor):
    # treat existing entries as last verified when they were created so they are not all instantly stale
    InventoryEntry = apps.get_model('cookbook', 'InventoryEntry')
    InventoryEntry.objects.filter(last_verified_at__isnull=True).update(last_verified_at=F('created_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0245_recipe_recommendation_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='verification_interval_days',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='inventoryentry',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='pantry_default_verification_days',
            field=models.PositiveIntegerField(
                default=14, help_text='Default number of days an inventory entry stays verified before it is considered stale. Used when the food has no interval set.'
            ),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='booking_type',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('move', 'Move'), ('check', 'Verify')], default='add', max_length=10),
        ),
        migrations.RunPython(backfill_last_verified, migrations.RunPython.noop),
    ]
