# Generated by Django 5.2.13 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0246_inventory_last_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
